-- local ok = pcall(require, "formatter")

-- if not ok then
-- 	vim.notify("formatter couldn't be loaded")
-- 	return
-- end

-- local prettier = function()
--     return {
--         exe = "npm run --silent prettier",
--         args = {
--             "--stdin-filepath",
--             vim.api.nvim_buf_get_name(0)
--         },
--         stdin = true
--     }
-- end

-- local prettier_php = function()
--     return {
--         exe = "npm run --silent prettier",
--         args = {
--             -- "--parser=php",
--             "--stdin-filepath",
--             vim.api.nvim_buf_get_name(0)
--         },
--         stdin = true
--     }
-- end

-- require("formatter").setup(
--     "formatter",
--     {
--         logging = false,
--         filetype = {
--             javascript = {prettier},
--             typescript = {prettier},
--             css = {prettier},
--             scss = {prettier},
--             php = {prettier_php},
--         }
--     }
-- )
--
--
-- NONE OF THIS IS WORKING AT THE MOMENT
